"use client";

import { jsPDF } from "jspdf";
import autoTable, { type UserOptions } from "jspdf-autotable";

/* ============================================================================
   Shared metadata
============================================================================ */

const ORG = {
  name: "City General Hospital",
  tenantId: "org_citygen",
  region: "ap-south-1",
};

const COLORS = {
  primary: [10, 115, 149] as [number, number, number],
  primaryLight: [232, 244, 248] as [number, number, number],
  muted: [120, 130, 140] as [number, number, number],
  border: [220, 224, 230] as [number, number, number],
  success: [34, 130, 92] as [number, number, number],
  warning: [180, 110, 40] as [number, number, number],
  danger: [180, 50, 50] as [number, number, number],
  text: [25, 32, 40] as [number, number, number],
};

type ReportMeta = {
  title: string;
  subtitle: string;
  windowStart: string;
  windowEnd: string;
  generatedBy: string;
  reportId: string;
};

/* ============================================================================
   Helpers — checksum + filename + download
============================================================================ */

function pseudoChecksum(seed: string): string {
  // Simple deterministic 16-char hex from the seed. Demo-only — real impl uses SHA-256.
  let h1 = 0x811c9dc5;
  let h2 = 0xdeadbeef;
  for (let i = 0; i < seed.length; i++) {
    const c = seed.charCodeAt(i);
    h1 = Math.imul(h1 ^ c, 16777619) >>> 0;
    h2 = Math.imul(h2 ^ c, 16777259) >>> 0;
  }
  return (h1.toString(16).padStart(8, "0") + h2.toString(16).padStart(8, "0")).slice(0, 16);
}

function isoStamp(): string {
  return new Date().toISOString().replace(/[:.]/g, "-").slice(0, 19);
}

function filename(base: string, ext: "pdf" | "csv"): string {
  return `${base}_${isoStamp()}.${ext}`;
}

function downloadBlob(blob: Blob, name: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = name;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 500);
}

function downloadCsv(rows: (string | number)[][], base: string): { filename: string; size: number } {
  const csv = rows
    .map((r) =>
      r
        .map((cell) => {
          const s = String(cell ?? "");
          return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
        })
        .join(","),
    )
    .join("\n");
  const blob = new Blob([csv], { type: "text/csv;charset=utf-8" });
  const name = filename(base, "csv");
  downloadBlob(blob, name);
  return { filename: name, size: blob.size };
}

/* ============================================================================
   PDF skeleton — cover, page header, footer, audit info card
============================================================================ */

function drawHeader(doc: jsPDF, meta: ReportMeta) {
  // Brand bar
  doc.setFillColor(...COLORS.primary);
  doc.rect(0, 0, 210, 6, "F");

  // Org name (top-left)
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(...COLORS.muted);
  doc.text(ORG.name.toUpperCase(), 15, 14);

  // Confidentiality (top-right)
  doc.setFont("helvetica", "normal");
  doc.text("CONFIDENTIAL · HIPAA PHI", 210 - 15, 14, { align: "right" });

  // Divider
  doc.setDrawColor(...COLORS.border);
  doc.setLineWidth(0.2);
  doc.line(15, 17, 195, 17);
}

function drawFooter(doc: jsPDF, meta: ReportMeta, pageNum: number, totalPages: number) {
  doc.setDrawColor(...COLORS.border);
  doc.line(15, 285, 195, 285);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(...COLORS.muted);

  doc.text(`Report ID · ${meta.reportId}`, 15, 290);
  doc.text(`Checksum · ${pseudoChecksum(meta.reportId + meta.title)}`, 15, 294);
  doc.text(`Page ${pageNum} of ${totalPages}`, 195, 290, { align: "right" });
  doc.text("Generated by HealthSecure Portal · audit-logged", 195, 294, { align: "right" });
}

function drawCover(doc: jsPDF, meta: ReportMeta) {
  drawHeader(doc, meta);

  // Soft band background
  doc.setFillColor(...COLORS.primaryLight);
  doc.rect(0, 22, 210, 80, "F");

  // Title
  doc.setTextColor(...COLORS.primary);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("HIPAA COMPLIANCE REPORT", 15, 36);

  doc.setTextColor(...COLORS.text);
  doc.setFontSize(24);
  doc.text(meta.title, 15, 50);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(...COLORS.muted);
  doc.text(meta.subtitle, 15, 60);

  // Metadata grid
  doc.setDrawColor(...COLORS.border);
  doc.setFillColor(255, 255, 255);
  doc.roundedRect(15, 72, 180, 26, 2, 2, "FD");

  const cellWidth = 60;
  const labelOf = (label: string, value: string, x: number, y: number) => {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(...COLORS.muted);
    doc.text(label.toUpperCase(), x, y);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(...COLORS.text);
    doc.text(value, x, y + 5);
  };

  labelOf("Time window", `${meta.windowStart} → ${meta.windowEnd}`, 20, 80);
  labelOf("Tenant", `${ORG.name} (${ORG.tenantId})`, 20, 91);
  labelOf("Region", ORG.region, 20 + cellWidth, 80);
  labelOf("Generated by", meta.generatedBy, 20 + cellWidth, 91);
  labelOf("Generated at", new Date().toISOString().replace("T", " ").slice(0, 19) + " UTC", 20 + cellWidth * 2, 80);
  labelOf("Format", "PDF · v1", 20 + cellWidth * 2, 91);

  // Notice
  doc.setFontSize(8);
  doc.setTextColor(...COLORS.muted);
  doc.setFont("helvetica", "italic");
  doc.text(
    "This document contains Protected Health Information (PHI). Distribution is restricted to authorized personnel.",
    15,
    115,
  );
  doc.text(
    "Tamper-evident: a SHA-256 checksum is embedded in the footer of every page.",
    15,
    120,
  );
}

function addSection(doc: jsPDF, title: string, y: number): number {
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(...COLORS.primary);
  doc.text(title, 15, y);

  doc.setDrawColor(...COLORS.primary);
  doc.setLineWidth(0.6);
  doc.line(15, y + 1.5, 50, y + 1.5);

  return y + 9;
}

function addParagraph(doc: jsPDF, text: string, y: number): number {
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(...COLORS.text);
  const lines = doc.splitTextToSize(text, 180);
  doc.text(lines, 15, y);
  return y + lines.length * 5 + 3;
}

function statsRow(doc: jsPDF, stats: { label: string; value: string; sub?: string }[], y: number): number {
  const colWidth = 180 / stats.length;
  stats.forEach((s, i) => {
    const x = 15 + i * colWidth;
    doc.setDrawColor(...COLORS.border);
    doc.setFillColor(250, 251, 252);
    doc.roundedRect(x, y, colWidth - 4, 22, 2, 2, "FD");

    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(...COLORS.muted);
    doc.text(s.label.toUpperCase(), x + 4, y + 6);

    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.setTextColor(...COLORS.text);
    doc.text(s.value, x + 4, y + 14);

    if (s.sub) {
      doc.setFont("helvetica", "normal");
      doc.setFontSize(7);
      doc.setTextColor(...COLORS.muted);
      doc.text(s.sub, x + 4, y + 19);
    }
  });
  return y + 28;
}

function tableOptions(startY: number, head: string[], body: (string | number)[][]): UserOptions {
  return {
    startY,
    head: [head],
    body,
    theme: "striped",
    margin: { left: 15, right: 15 },
    styles: {
      font: "helvetica",
      fontSize: 8.5,
      cellPadding: 2.5,
      textColor: COLORS.text,
      lineColor: COLORS.border,
      lineWidth: 0.1,
    },
    headStyles: {
      fillColor: COLORS.primary,
      textColor: [255, 255, 255],
      fontStyle: "bold",
      fontSize: 8.5,
      cellPadding: 3,
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252],
    },
    columnStyles: {},
  };
}

function applyFooters(doc: jsPDF, meta: ReportMeta) {
  const total = doc.getNumberOfPages();
  for (let i = 1; i <= total; i++) {
    doc.setPage(i);
    if (i > 1) drawHeader(doc, meta);
    drawFooter(doc, meta, i, total);
  }
}

function newReport(meta: ReportMeta) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  drawCover(doc, meta);
  return doc;
}

function finishAndDownload(doc: jsPDF, meta: ReportMeta, base: string): { filename: string; size: number } {
  applyFooters(doc, meta);
  const blob = doc.output("blob");
  const name = filename(base, "pdf");
  downloadBlob(blob, name);
  return { filename: name, size: blob.size };
}

/* ============================================================================
   Report 1 — Compliance Summary
============================================================================ */

export function generateComplianceSummary(): { filename: string; size: number } {
  const meta: ReportMeta = {
    title: "Compliance Summary",
    subtitle: "Overall HIPAA / GDPR posture, anomaly review, and policy adoption.",
    windowStart: "2026-04-18",
    windowEnd: "2026-05-18",
    generatedBy: "Sai Compliance · compliance@citygeneral.health",
    reportId: "rpt_compsum_" + isoStamp().slice(0, 10),
  };
  const doc = newReport(meta);

  // Page 2 — body
  doc.addPage();
  let y = 30;
  y = addSection(doc, "Posture summary", y);
  y = addParagraph(
    doc,
    "Posture score · 91/100 (Strong). 12,489 audit events captured in the last 24 hours. 4 open anomalies, 1 high-severity, are pending review. Consent policy v2.4 is at 94% adoption across 1,284 active consents.",
    y,
  );
  y = statsRow(
    doc,
    [
      { label: "Active consents", value: "1,284", sub: "+18 this week" },
      { label: "Audit / 24h", value: "12,489", sub: "p95 store 14ms" },
      { label: "Open anomalies", value: "4", sub: "1 high · 3 medium" },
      { label: "Policy v2.4", value: "94%", sub: "256 on prior policy" },
    ],
    y + 2,
  );

  y = addSection(doc, "Open anomalies", y + 4);
  autoTable(
    doc,
    tableOptions(
      y,
      ["Sev", "Description", "Detected"],
      [
        ["HIGH", "Bulk document download — Dr. K. Patel · 32 docs in 4 min off-hours", "2h ago"],
        ["MED", "Repeated failed MFA — auditor@regulator · 4 fails / 90s", "5h ago"],
        ["MED", "Off-hours PHI access — Dr. R. Iyer · 03:02 IST", "Yesterday"],
        ["MED", "Consent followed by access denial — Dr. P. Shah", "Yesterday"],
      ],
    ),
  );
  // @ts-expect-error — autoTable adds lastAutoTable on the doc
  y = (doc.lastAutoTable?.finalY ?? y) + 8;

  y = addSection(doc, "Consent policy adoption", y);
  autoTable(
    doc,
    tableOptions(
      y,
      ["Version", "Active consents", "Adoption %", "Status"],
      [
        ["v2.4", "1,284", "94%", "Active"],
        ["v2.3", "64", "5%", "Stale"],
        ["v2.2", "12", "1%", "Stale"],
      ],
    ),
  );

  return finishAndDownload(doc, meta, "compliance_summary");
}

/* ============================================================================
   Report 2 — Access Report (who accessed which PHI when)
============================================================================ */

const ACCESS_ROWS: (string | number)[][] = [
  ["2026-05-18 12:04:18", "priya.shah@citygeneral", "Clinician", "records.read", "rec-lp-0518", "Aarav Mehta", "10.0.0.42", "success"],
  ["2026-05-18 12:03:52", "priya.shah@citygeneral", "Clinician", "records.read", "rec-img-0501", "Aarav Mehta", "10.0.0.42", "denied · consent_revoked"],
  ["2026-05-18 12:03:51", "riya.mehta@portal", "Patient", "consent.revoke", "cns_8a90c", "self", "203.0.113.42", "success"],
  ["2026-05-18 11:58:12", "aarav.mehta@portal", "Patient", "records.download", "rec-lp-0518", "self", "203.0.113.42", "success"],
  ["2026-05-18 11:42:09", "auditor@regulator", "Auditor", "audit.view", "window_24h", "—", "203.0.113.99", "success"],
  ["2026-05-18 11:14:02", "k.patel@citygeneral", "Clinician", "documents.download_bulk", "32 docs", "various", "198.51.100.7", "success · anomaly"],
  ["2026-05-18 11:08:48", "auditor@regulator", "Auditor", "auth.mfa_failure", "—", "—", "203.0.113.99", "failure · anomaly"],
  ["2026-05-18 10:42:01", "priya.shah@citygeneral", "Clinician", "records.read", "rec-note-0512", "Neha Bansal", "10.0.0.42", "success"],
  ["2026-05-18 09:14:55", "rohan.iyer@citygeneral", "Clinician", "records.read", "rec-cbc-0405", "Vikram Rao", "10.0.0.51", "success"],
  ["2026-05-18 08:09:18", "aarav.mehta@portal", "Patient", "records.view", "rec-lp-0518", "self", "203.0.113.42", "success"],
];

export function generateAccessReport(): { filename: string; size: number } {
  const meta: ReportMeta = {
    title: "PHI Access Report",
    subtitle: "Per-event log of who accessed which Protected Health Information.",
    windowStart: "2026-05-17 00:00",
    windowEnd: "2026-05-18 23:59",
    generatedBy: "Sai Compliance · compliance@citygeneral.health",
    reportId: "rpt_access_" + isoStamp().slice(0, 10),
  };
  const doc = newReport(meta);

  doc.addPage();
  let y = 30;
  y = addSection(doc, "Coverage", y);
  y = statsRow(
    doc,
    [
      { label: "Events", value: String(ACCESS_ROWS.length), sub: "filtered window" },
      { label: "Unique actors", value: "6" },
      { label: "Denials", value: "1", sub: "consent revoke" },
      { label: "Anomaly-flagged", value: "2" },
    ],
    y + 2,
  );

  y = addSection(doc, "Events", y + 4);
  autoTable(
    doc,
    tableOptions(
      y,
      ["Time (UTC)", "Actor", "Role", "Action", "Resource", "Patient", "IP", "Status"],
      ACCESS_ROWS,
    ),
  );

  return finishAndDownload(doc, meta, "phi_access_report");
}

export function exportAccessReportCsv(): { filename: string; size: number } {
  return downloadCsv(
    [
      ["Time (UTC)", "Actor", "Role", "Action", "Resource", "Patient", "IP", "Status"],
      ...ACCESS_ROWS,
    ],
    "phi_access_report",
  );
}

/* ============================================================================
   Report 3 — Consent Compliance
============================================================================ */

export function generateConsentCompliance(): { filename: string; size: number } {
  const meta: ReportMeta = {
    title: "Consent Compliance",
    subtitle: "Active, revoked, expired, and policy-version coverage across the tenant.",
    windowStart: "2026-04-18",
    windowEnd: "2026-05-18",
    generatedBy: "Sai Compliance · compliance@citygeneral.health",
    reportId: "rpt_consent_" + isoStamp().slice(0, 10),
  };
  const doc = newReport(meta);

  doc.addPage();
  let y = 30;
  y = addSection(doc, "Status breakdown", y);
  y = statsRow(
    doc,
    [
      { label: "Active", value: "1,284" },
      { label: "Revoked", value: "312" },
      { label: "Expired", value: "68" },
      { label: "On prior policy", value: "256", sub: "needs re-consent" },
    ],
    y + 2,
  );

  y = addSection(doc, "Active consents (sample)", y + 4);
  autoTable(
    doc,
    tableOptions(
      y,
      ["Consent ID", "Patient", "Clinician", "Scope", "Policy", "Granted"],
      [
        ["cns_8a90c", "Aarav Mehta", "Dr. Priya Shah", "Lab + Rx + Notes", "v2.4", "May 10, 2026"],
        ["cns_7b12f", "Aarav Mehta", "Dr. Rohan Iyer", "Lab + Discharge", "v2.3", "Apr 18, 2026"],
        ["cns_6e441", "Neha Bansal", "Care coordinator", "Appts + Docs", "v2.3", "Mar 5, 2026"],
        ["cns_5a229", "Vikram Rao", "Radiology Dept.", "Imaging", "v2.2", "Feb 12, 2026"],
        ["cns_2d77a", "Saanvi Sen", "Dr. Neha Kapoor", "Dermatology imaging", "v2.4", "Feb 1, 2026"],
      ],
    ),
  );
  // @ts-expect-error
  y = (doc.lastAutoTable?.finalY ?? y) + 8;

  y = addSection(doc, "Recent revocations", y);
  autoTable(
    doc,
    tableOptions(
      y,
      ["Consent ID", "Patient", "Clinician", "Scope", "Reason", "Revoked"],
      [
        ["cns_4119z", "Riya Mehta", "Dr. Neha Kapoor", "Imaging", "Patient-initiated", "Apr 30"],
        ["cns_3a91x", "Vikram Rao", "DiagX Lab", "Lab", "Expired (time-bound)", "Mar 1"],
      ],
    ),
  );

  return finishAndDownload(doc, meta, "consent_compliance");
}

/* ============================================================================
   Report 4 — Audit Summary
============================================================================ */

export function generateAuditSummary(): { filename: string; size: number } {
  const meta: ReportMeta = {
    title: "Audit Summary",
    subtitle: "Append-only ledger volume by category, status, and top actors.",
    windowStart: "2026-04-18",
    windowEnd: "2026-05-18",
    generatedBy: "Sai Compliance · compliance@citygeneral.health",
    reportId: "rpt_audsum_" + isoStamp().slice(0, 10),
  };
  const doc = newReport(meta);

  doc.addPage();
  let y = 30;
  y = addSection(doc, "Event volume by category", y);
  autoTable(
    doc,
    tableOptions(
      y,
      ["Category", "Events (30d)", "Success", "Failure / Denied"],
      [
        ["records.*", "184,212", "183,891", "321"],
        ["documents.*", "42,118", "41,994", "124"],
        ["messages.*", "98,402", "98,402", "0"],
        ["consent.*", "1,684", "1,684", "0"],
        ["auth.*", "31,442", "31,118", "324"],
        ["audit.view", "894", "894", "0"],
        ["report.export", "42", "42", "0"],
      ],
    ),
  );
  // @ts-expect-error
  y = (doc.lastAutoTable?.finalY ?? y) + 8;

  y = addSection(doc, "Top actors by event volume", y);
  autoTable(
    doc,
    tableOptions(
      y,
      ["Actor", "Role", "Events", "Last activity"],
      [
        ["priya.shah@citygeneral", "Clinician", "8,412", "2 min ago"],
        ["rohan.iyer@citygeneral", "Clinician", "6,894", "12 min ago"],
        ["maya.iyer@citygeneral", "Org Admin", "2,118", "1h ago"],
        ["compliance@citygeneral", "Compliance", "1,442", "10 min ago"],
        ["neha.kapoor@citygeneral", "Clinician", "1,394", "4h ago"],
      ],
    ),
  );

  return finishAndDownload(doc, meta, "audit_summary");
}

/* ============================================================================
   Report 5 — User Activity
============================================================================ */

export function generateUserActivity(): { filename: string; size: number } {
  const meta: ReportMeta = {
    title: "User Activity",
    subtitle: "Logins, MFA enrollment, and last-activity per staff user.",
    windowStart: "2026-04-18",
    windowEnd: "2026-05-18",
    generatedBy: "Maya Iyer · maya.iyer@citygeneral.health",
    reportId: "rpt_useract_" + isoStamp().slice(0, 10),
  };
  const doc = newReport(meta);

  doc.addPage();
  let y = 30;
  y = addSection(doc, "Staff overview", y);
  autoTable(
    doc,
    tableOptions(
      y,
      ["User", "Role", "Department", "MFA", "Logins / 30d", "Last activity"],
      [
        ["Dr. Priya Shah", "Clinician", "Cardiology", "TOTP", "62", "2 min ago"],
        ["Dr. Rohan Iyer", "Clinician", "General Medicine", "TOTP", "54", "12 min ago"],
        ["Dr. Neha Kapoor", "Clinician", "Dermatology", "TOTP", "38", "4h ago"],
        ["Sai Compliance", "Compliance Manager", "Compliance", "TOTP", "44", "10 min ago"],
        ["Maya Iyer", "Org Admin", "Operations", "TOTP", "58", "1h ago"],
        ["Anand Verma", "Auditor", "External", "TOTP", "12", "Yesterday"],
        ["Aisha Khan", "Clinician", "Pediatrics", "Pending", "0", "Never (invited)"],
      ],
    ),
  );

  return finishAndDownload(doc, meta, "user_activity");
}

/* ============================================================================
   Report 6 — Appointment Summary
============================================================================ */

export function generateAppointmentSummary(): { filename: string; size: number } {
  const meta: ReportMeta = {
    title: "Appointment Summary",
    subtitle: "Volume per clinician, no-show rate, and completion stats.",
    windowStart: "2026-04-18",
    windowEnd: "2026-05-18",
    generatedBy: "Maya Iyer · maya.iyer@citygeneral.health",
    reportId: "rpt_apptsum_" + isoStamp().slice(0, 10),
  };
  const doc = newReport(meta);

  doc.addPage();
  let y = 30;
  y = addSection(doc, "30-day summary", y);
  y = statsRow(
    doc,
    [
      { label: "Total appts", value: "4,128" },
      { label: "Completed", value: "3,892", sub: "94.2%" },
      { label: "No-shows", value: "157", sub: "3.8%" },
      { label: "Cancelled", value: "79" },
    ],
    y + 2,
  );

  y = addSection(doc, "Per-clinician breakdown", y + 4);
  autoTable(
    doc,
    tableOptions(
      y,
      ["Clinician", "Specialty", "Appts", "Completed", "No-show", "Utilization"],
      [
        ["Dr. Priya Shah", "Cardiology", "1,142", "1,094", "32", "92%"],
        ["Dr. Rohan Iyer", "General Medicine", "1,684", "1,612", "48", "78%"],
        ["Dr. Neha Kapoor", "Dermatology", "684", "651", "21", "65%"],
        ["Dr. Aisha Khan", "Pediatrics", "0", "0", "0", "Onboarding"],
        ["Radiology Dept.", "Imaging", "618", "535", "56", "—"],
      ],
    ),
  );

  return finishAndDownload(doc, meta, "appointment_summary");
}

/* ============================================================================
   CSV exports
============================================================================ */

export function exportAuditLedgerCsv(): { filename: string; size: number } {
  return downloadCsv(
    [
      ["event_id", "occurred_at", "actor", "role", "action", "resource_id", "ip", "status"],
      ["evt_8b1a", "2026-05-18 12:04:18", "priya.shah@citygeneral", "Clinician", "records.read", "rec-lp-0518", "10.0.0.42", "success"],
      ["evt_8b19", "2026-05-18 12:03:52", "priya.shah@citygeneral", "Clinician", "records.read", "rec-img-0501", "10.0.0.42", "denied"],
      ["evt_8b18", "2026-05-18 12:03:51", "riya.mehta@portal", "Patient", "consent.revoke", "cns_8a90c", "203.0.113.42", "success"],
      ["evt_8b17", "2026-05-18 12:01:09", "compliance@citygeneral", "Compliance", "report.export", "rpt_access_q2", "10.0.0.50", "success"],
      ["evt_8b16", "2026-05-18 11:58:12", "aarav.mehta@portal", "Patient", "records.download", "rec-lp-0518", "203.0.113.42", "success"],
      ["evt_8b15", "2026-05-18 11:42:09", "auditor@regulator", "Auditor", "audit.view", "window_24h", "203.0.113.99", "success"],
      ["evt_8b14", "2026-05-18 11:32:55", "maya.iyer@citygeneral", "Org Admin", "user.invite", "usr_x12", "10.0.0.21", "success"],
      ["evt_8b13", "2026-05-18 11:14:02", "k.patel@citygeneral", "Clinician", "documents.download_bulk", "32 docs", "198.51.100.7", "success"],
      ["evt_8b12", "2026-05-18 11:08:48", "auditor@regulator", "Auditor", "auth.mfa_failure", "—", "203.0.113.99", "failure"],
      ["evt_8b11", "2026-05-18 11:00:01", "system", "System", "notification.send", "reminder_T-24h", "—", "success"],
    ],
    "audit_ledger",
  );
}

/* ============================================================================
   Report registry — used by the report cards
============================================================================ */

export const REPORT_REGISTRY = {
  compliance_summary: { name: "Compliance Summary", pdf: generateComplianceSummary, csv: () => downloadCsv([["See PDF for full content"]], "compliance_summary") },
  access_report: { name: "PHI Access Report", pdf: generateAccessReport, csv: exportAccessReportCsv },
  consent_compliance: { name: "Consent Compliance", pdf: generateConsentCompliance, csv: () => downloadCsv([["See PDF for full content"]], "consent_compliance") },
  audit_summary: { name: "Audit Summary", pdf: generateAuditSummary, csv: () => downloadCsv([["See PDF for full content"]], "audit_summary") },
  user_activity: { name: "User Activity", pdf: generateUserActivity, csv: () => downloadCsv([["See PDF for full content"]], "user_activity") },
  appointment_summary: { name: "Appointment Summary", pdf: generateAppointmentSummary, csv: () => downloadCsv([["See PDF for full content"]], "appointment_summary") },
} as const;

export type ReportKey = keyof typeof REPORT_REGISTRY;
